apiVersion: v1
kind: Secret
metadata:
  name: {{ template "growi.fullname" . }}
  labels:
    {{- include "growi.labels" . | nindent 4 }}
type: Opaque
data:
    {{- if .Values.passwordSeed }}
    PASSWORD_SEED: {{ .Values.passwordSeed | b64enc | quote }}
    {{- else }}
    PASSWORD_SEED: {{ randAlphaNum 10 | b64enc | quote }}
    {{- end }}

