dependencies:
- name: mongodb
  version: 9.2.2
  # TODO: change to the location of current helm charts
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  condition: mongodb.enabled
- name: elasticsearch
  version: 7.9.2
  repository: https://helm.elastic.co/
  condition: elasticsearch.enabled
